---
# Deployment for the Slurm Chat application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm-chat-deployment
  namespace: slurm-chat
  labels:
    app: slurm-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurm-chat
  template:
    metadata:
      labels:
        app: slurm-chat
    spec:
      containers:
      - name: slurm-chat
        image: rkhoja/alliance-chat:latest
        imagePullPolicy: Always
        env:
          - name: AI_PROVIDER
            value: "OLLAMA" # Replace with your value
          - name: AI_MODEL_A
            value: "deepseek-r1:671b" # Replace with your value
          - name: AI_MODEL_B
            value: "command-r-plus:latest" # Replace with your value
          - name: SECRET_KEY
            value: "123456586789698798798"
          - name: RAGFLOW_API_URL
            value: "https://1.2.3.4"
          - name: GOOGLE_AI_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: GOOGLE_AI_API_KEY
          - name: ANTHROPIC_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ANTHROPIC_API_KEY
          - name: GROQ_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: GROQ_API_KEY
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: OPENAI_API_KEY
          - name: RAGIE_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RAGIE_API_KEY
          - name: RAGFLOW_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RAGFLOW_API_KEY
        ports:
        - containerPort: 8000

---
# Service to expose the application internally
apiVersion: v1
kind: Service
metadata:
  name: slurm-chat-service
  namespace: slurm-chat
spec:
  selector:
    app: slurm-chat
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP

---
# Certificate for SSL via cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-cluster-paice-ua-com
  namespace: slurm-chat
spec:
  secretName: chat-cluster-paice-ua-com-tls
  issuerRef:
    name: letsencrypt-dns # Assumes this ClusterIssuer exists
    kind: ClusterIssuer
  commonName: chat.cluster.paice-ua.com
  dnsNames:
    - chat.cluster.paice-ua.com

---
# Ingress for public access with SSL
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slurm-chat-ingress
  namespace: slurm-chat
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true" # Explicitly enable TLS
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - chat.cluster.paice-ua.com
    secretName: chat-cluster-paice-ua-com-tls # Matches Certificate secretName
  rules:
  - host: chat.cluster.paice-ua.com # Only responds to this hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slurm-chat-service
            port:
              number: 8000
