import os

class Config:
    LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG')
    SECRET_KEY = os.getenv('SECRET_KEY', '87P64E34f9d56fumHa2OQg8aCTp7h8Zl')
    SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI', "sqlite:///./chat.db")
    SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS', 'False')
    if SQLALCHEMY_TRACK_MODIFICATIONS.upper() == "FALSE":
        SQLALCHEMY_TRACK_MODIFICATIONS = False
    else:
        SQLALCHEMY_TRACK_MODIFICATIONS = True	
    GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID')
    if GOOGLE_ANALYTICS_ID and GOOGLE_ANALYTICS_ID.upper() == 'NONE':
        GOOGLE_ANALYTICS_ID = None
    GOOGLE_SITE_VERIFICATION = os.getenv('GOOGLE_SITE_VERIFICATION')
    if GOOGLE_SITE_VERIFICATION and GOOGLE_SITE_VERIFICATION.upper() == 'NONE':
        GOOGLE_SITE_VERIFICATION = None
    BING_SITE_VERIFICATION = os.getenv('BING_SITE_VERIFICATION')
    if BING_SITE_VERIFICATION and BING_SITE_VERIFICATION.upper() == 'NONE':
        BING_SITE_VERIFICATION = None
    SYSTEM_MAINTENANCE_MODE = os.getenv('SYSTEM_MAINTENANCE_MODE', 'False')
    ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
    GROQ_API_KEY = os.getenv('GROQ_API_KEY')
    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')    
    RAGIE_API_KEY = os.getenv('RAGIE_API_KEY')  
    RAGFLOW_API_KEY = os.getenv('RAGFLOW_API_KEY') 
    RAGFLOW_API_URL = os.getenv('RAGFLOW_API_URL') 
    GOOGLE_AI_API_KEY = os.getenv('GOOGLE_AI_API_KEY')
    AI_MODEL_A = os.getenv('AI_MODEL_A')    
    AI_MODEL_B = os.getenv('AI_MODEL_B')
    AI_PROVIDER = os.getenv('AI_PROVIDER')
    OLLAMA_BASE_URL = "http://64.181.202.213:11434"
